tap "homebrew/bundle"
brew "python@3.13"
brew "glib"
brew "harfbuzz"
brew "libxmlb"
brew "libadwaita"
brew "baobab"
brew "cmake"
brew "tesseract"
brew "ffmpeg"
brew "git-lfs"
brew "mas"
brew "openjdk"
brew "pandoc"
brew "python-tk@3.12"
brew "qpdf"
brew "tailscale"
brew "tree"
brew "yadm"
cask "appcleaner"
cask "arc"
cask "calibre", args: { appdir: "/Applications" }
cask "claude"
cask "docker", args: { appdir: "/Applications" }
cask "google-drive", args: { appdir: "/Applications" }
cask "hazeover"
cask "jetbrains-toolbox", args: { appdir: "/Applications" }
cask "keka", args: { appdir: "/Applications" }
cask "lyx", args: { appdir: "/Applications" }
cask "macs-fan-control", args: { appdir: "/Applications" }
cask "mactex", args: { appdir: "/Applications" }
cask "mathpix-snipping-tool", args: { appdir: "/Applications" }
cask "miniconda", args: { appdir: "/Applications" }
cask "onyx"
cask "orion"
cask "qbittorrent", args: { appdir: "/Applications" }
cask "raspberry-pi-imager", args: { appdir: "/Applications" }
cask "sioyek", args: { appdir: "/Applications" }
cask "subler", args: { appdir: "/Applications" }
cask "tikzit", args: { appdir: "/Applications" }
cask "time-out", args: { appdir: "/Applications" }
cask "utm"
cask "visual-studio-code"
cask "vlc", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "one sec", id: 1532875441
mas "Sorted", id: 1306893526
mas "Tailscale", id: 1475387142
mas "TickTick", id: 966085870
mas "Toggl Track", id: 1291898086
vscode "asciidoctor.asciidoctor-vscode"
vscode "bierner.markdown-mermaid"
vscode "davidanson.vscode-markdownlint"
vscode "eamodio.gitlens"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "gruntfuggly.todo-tree"
vscode "hediet.vscode-drawio"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.datawrangler"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.copilot-mermaid-diagram"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "yzhang.markdown-all-in-one"
vscode "zhouronghui.propertylist"
