#!/usr/bin/env zsh
# created by gilad ticher

echo "Setting up LyX..."
if [ -d ~/Library/Application\ Support/LyX-2.4 ]; then
    # Install Culmus fonts
    mkdir -p $HOME/.tmp
    cd .tmp
    tar -xvf $HOME/.config/lyx/culmus-0.133.tar.gz
    cd culmus-0.133
    cp -a . /Library/Fonts/
    cd ../..
    rm -rf $HOME/.tmp

    # Create symlinks for LyX user preferences
    ln -sf "$HOME/.config/lyx/preferences" "$HOME/Library/Application Support/LyX-2.4/preferences"
    ln -sf "$HOME/.config/lyx/templates/defaults.lyx" "$HOME/Library/Application Support/LyX-2.4/templates/defaults.lyx"
    echo "Finished setting up LyX."
else
    echo "LyX not installed."
fi
